const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
const html=fs.readFileSync(require('node:path').join(__dirname,'../index.html'),'utf8');
const helper=html.split('// DRUG_WEBVIEW_LOAD_LIFECYCLE_V1_BEGIN')[1].split('// DRUG_WEBVIEW_LOAD_LIFECYCLE_V1_END')[0];
function setup(fetch){const c={fetch,AbortController,setTimeout,clearTimeout};vm.createContext(c);vm.runInContext(helper+';this.load=fetchDrugCard;this.reason=drugLoadCode;',c);return c;}
test('successful card keeps payload unchanged and canonical URL encoded',async()=>{let url;const payload={id:'fixture',pt:{name:'Fixture'}};const c=setup(async(u)=>{url=u;return{ok:true,json:async()=>payload}});assert.equal(await c.load('fixture.json'),payload);assert.equal(url,'data/drugs/fixture.json')});
for(const [status,code] of [[401,'AUTH_ERROR'],[403,'AUTH_ERROR'],[404,'ROUTE_NOT_FOUND'],[429,'HTTP_4XX'],[500,'HTTP_5XX']])test('HTTP '+status+' has a bounded recoverable reason',async()=>{const c=setup(async()=>({ok:false,status}));await assert.rejects(c.load('fixture.json'),e=>c.reason(e)==='DRUG_WEBVIEW_'+code)});
test('network timeout settles even when transport ignores abort',async()=>{const c=setup(()=>new Promise(()=>{}));await assert.rejects(c.load('fixture.json',10),e=>c.reason(e)==='DRUG_WEBVIEW_TIMEOUT')});
test('JSON body timeout is also bounded',async()=>{const c=setup(async()=>({ok:true,json:()=>new Promise(()=>{})}));await assert.rejects(c.load('fixture.json',10),e=>c.reason(e)==='DRUG_WEBVIEW_TIMEOUT')});
test('malformed response never becomes a ready card',async()=>{const c=setup(async()=>({ok:true,json:async()=>[]}));await assert.rejects(c.load('fixture.json'),e=>c.reason(e)==='DRUG_WEBVIEW_JS_ERROR')});
test('expired bridge is classified without logging sensitive error',()=>{const c=setup();assert.equal(c.reason(new Error('MCC1_SESSION_EXPIRED')),'DRUG_WEBVIEW_AUTH_ERROR');assert.equal(c.reason(new Error('private text')),'DRUG_WEBVIEW_UNKNOWN')});
// Execute the production renderer with inert presentation doubles, so these
// tests exercise selection ownership and failed/pending transitions, not content.
function renderer(fetch){const node=()=>({dataset:{},style:{setProperty(){}},textContent:'',hidden:false,disabled:false,setAttribute(){},removeAttribute(){},appendChild(){},querySelector(){return this},querySelectorAll(){return[]},insertAdjacentElement(){}});const page=node();const ui={page};for(const k of ['tt','eye','name','klass','al','ai','wl','wi','cb','rl','rt','loading'])ui[k]=node();let locale='es';const c={BUILD:'test',fetch,AbortController,setTimeout:()=>0,clearTimeout,console:{log(){},warn(){}},Element:class{},window:{addEventListener(){}},document:{getElementById:()=>({classList:{contains:()=>true}}),createElement:node},S:{cache:new Map()},ensure:()=>ui,lang:()=>locale,mk:node,P:()=>({name:[],klass:[]}),L:{es:{loading:'Loading'},pt:{loading:'Loading'}},first:()=>'',has:()=>false,sec:()=>{},provider:()=>{},secCommercial:()=>{},commercialFor:()=>[],ORDER:[],sig:()=>'',bridge:()=>{},result:()=>{},show:()=>{},polishCanonicalDom:()=>{},r5Finalize:()=>{}};vm.createContext(c);
const lifecycle=html.slice(html.indexOf('const loadState={generation:0'),html.indexOf('const underlying=()=>'));
const render=html.slice(html.indexOf('const render=async(drug,why,directOnly=false)=>'),html.indexOf('const reconcile=(why,force=false)=>'));
vm.runInContext(helper+ lifecycle+render+';this.render=render;this.state=loadState;',c);return{c,ui,locale:v=>locale=v};}
test('failed load disables controls and remains an error on repeated reconciliation',async()=>{let calls=0;const {c,ui}=renderer(async()=>{calls++;return{ok:false,status:404}});await c.render('a','test',true);assert.equal(ui.page.dataset.mcCardReady,'false');assert.equal(ui.ai.disabled,true);assert.equal(ui.cb.disabled,true);assert.match(ui.loading.textContent,/No pudimos/);await c.render('a','observer',true);assert.equal(calls,1);assert.match(ui.loading.textContent,/No pudimos/)});
test('PT localized recoverable message',async()=>{const {c,ui,locale}=renderer(async()=>({ok:false,status:500}));locale('pt');await c.render('a','test',true);assert.match(ui.loading.textContent,/Não foi possível/)});
test('selection B wins when slower selection A completes late',async()=>{let resolveA;const {c,ui}=renderer(u=>u.includes('a.json')?new Promise(r=>resolveA=r):Promise.resolve({ok:true,json:async()=>({id:'b'})}));const pending=c.render('a','test',true);await c.render('b','test',true);resolveA({ok:true,json:async()=>({id:'a'})});await pending;assert.equal(ui.page.dataset.mcDrugId,'b');assert.equal(c.S.data.id,'b');assert.equal(ui.page.dataset.mcCardReady,'true')});
test('explicit retry recovers without discarding selected identity',async()=>{let fail=true;const {c,ui}=renderer(async()=>fail?({ok:false,status:500}):({ok:true,json:async()=>({id:'a'})}));await c.render('a','test',true);fail=false;c.state.failed=false;await c.render(c.state.key,'explicit-retry',true);assert.equal(ui.page.dataset.mcDrugId,'a');assert.equal(ui.page.dataset.mcCardReady,'true')});
