#!/usr/bin/env node
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import { execFileSync, spawnSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

const repo=path.resolve(import.meta.dirname,'..'), tmp=fs.mkdtempSync(path.join(os.tmpdir(),'gold33-sync-test-'));
const fields=['name','class','pharmacologicClass','commercialNames','presentation','presentations','mechanism','pharmacodynamics','pharmacokinetics','indications','dose','pediatricDose','renalDose','hepaticDose','commonAdverseEffects','dangerousAdverseEffects','adverseEffects','contraindications','interactions','monitoring','administration','preparation','infusionProtocol','pregnancy','lactation','specialPopulations','patientEducation','clinicalPearls','guidelineRecommendations','safetyFlags','alerts','references','ref'];
const ids=['aas_antiagregante','abacavir','abatacepte','abciximabe','acamprosato','aceclofenaco','acenocumarol','acetato_de_calcio','acetazolamida','acetilcisteina'];
const owners={aas_antiagregante:['database/anticoag.js','ANTICOAG_DRUGS_DB'],abacavir:['database/infectologia.js','INFECTOLOGIA_DRUGS_DB'],abatacepte:['database/reumatologia.js','REUMATOLOGIA_DRUGS_DB'],abciximabe:['database/cardio.js','CARDIO_DRUGS_DB'],acamprosato:['database/toxicologia.js','TOXICOLOGIA_DRUGS_DB'],aceclofenaco:['database/analgesicos.js','ANALGESICOS_DRUGS_DB'],acenocumarol:['database/cardio.js','CARDIO_DRUGS_DB'],acetato_de_calcio:['database/nefro.js','NEFRO_DRUGS_DB'],acetazolamida:['database/cardio.js','CARDIO_DRUGS_DB'],acetilcisteina:['database/emergencia.js','EMERGENCIA_DRUGS_DB']};
const sha=(b)=>crypto.createHash('sha256').update(b).digest('hex');
function copyRoot(dst){fs.mkdirSync(dst,{recursive:true});for(const d of ['database','data','public','gateway','scripts'])fs.cpSync(path.join(repo,d),path.join(dst,d),{recursive:true});fs.copyFileSync(path.join(repo,'package.json'),path.join(dst,'package.json'));fs.writeFileSync(path.join(dst,'.gold33-architecture-approved'),'synthetic-test-only\n');}
function makeZip(dir,batch){const p=path.join(dir,'pkg');fs.mkdirSync(p);const rows=batch.map(id=>({ID:id,NOTA_REVISAO_CLINICA:'SYNTHETIC TEST DATA — NO CLINICAL CONTENT',CAMPOS_33:Object.fromEntries(fields.map(f=>[f,f==='references'?[]:{pt:`SYNTHETIC_${id}_${f}_PT`,es:`SYNTHETIC_${id}_${f}_ES`}]))}));const data=JSON.stringify(rows,null,2)+'\n';fs.writeFileSync(path.join(p,'01_DADOS_HOMOLOGADOS.json'),data);const opinion={lote:'SYNTHETIC',homologation:{REVISAO_CLINICA:'HOMOLOGADA',STATUS_DADOS:'APROVADOS_CLINICAMENTE'},scope:{ids:batch,canonical_fields:fields},final_consolidation:{final_sha256:sha(data)}};fs.writeFileSync(path.join(p,'04_PARECER_CLINICO.json'),JSON.stringify(opinion,null,2)+'\n');const allow=JSON.parse(fs.readFileSync(path.join(dir,'gateway/data/free60_allowlist.v2.json'))).ids;const items=batch.map(id=>({id,source_executavel:owners[id][0],owner_canonico:owners[id][1],derived_private_json:`data/drugs/${id}.json`,states:{PUBLICACAO:allow.includes(id)?'LIBERADA':'BLOQUEADA'}}));const restrictions={global:{INTEGRACAO_TECNICA:'LIBERADA',AUTORIZACAO_DE_CALCULO:'BLOQUEADA',PUBLICACAO:'CONDICIONAL'},items};fs.writeFileSync(path.join(p,'05_RESTRICOES_E_PENDENCIAS.json'),JSON.stringify(restrictions,null,2)+'\n');for(const n of ['02_ALTERACOES_APROVADAS.json','03_REFERENCIAS.md','07_CONTRATO_CODEX.md'])fs.writeFileSync(path.join(p,n),n.endsWith('.json')?'{}\n':'SYNTHETIC\n');const covered=['01_DADOS_HOMOLOGADOS.json','02_ALTERACOES_APROVADAS.json','03_REFERENCIAS.md','04_PARECER_CLINICO.json','05_RESTRICOES_E_PENDENCIAS.json','07_CONTRATO_CODEX.md'];fs.writeFileSync(path.join(p,'06_MANIFESTO_SHA256.txt'),covered.map(n=>`${sha(fs.readFileSync(path.join(p,n)))}  ${n}`).join('\n')+'\n');const zip=path.join(dir,`synthetic-${batch.length}.zip`);execFileSync('zip',['-q',zip,...covered,'06_MANIFESTO_SHA256.txt'],{cwd:p});return zip;}
function run(root,zip,extra=[],env={}){return spawnSync(process.execPath,['scripts/gold33-selective-sync.mjs','--root',root,'--zip',zip,...extra],{cwd:root,encoding:'utf8',env:{...process.env,GOLD33_SYNTHETIC_TEST:'1',...env}})}
try{
 const one=path.join(tmp,'one');copyRoot(one);const oneZip=makeZip(one,[ids[0]]);const outside=fs.readFileSync(path.join(one,'data/drugs/abacavir.json'));let r=run(one,oneZip,['--apply']);assert.equal(r.status,0,r.stderr);assert.ok(fs.readFileSync(path.join(one,'database/anticoag.js'),'utf8').includes('GOLD33_SELECTIVE:aas_antiagregante:START'));assert.ok(fs.readFileSync(path.join(one,'data/drugs/abacavir.json')).equals(outside));assert.ok(!fs.existsSync(path.join(one,'public/data/drugs/aas_antiagregante.json')),'Premium must remain private');const after=fs.readFileSync(path.join(one,'database/anticoag.js'));r=run(one,oneZip,['--apply']);assert.equal(r.status,0,r.stderr);assert.ok(fs.readFileSync(path.join(one,'database/anticoag.js')).equals(after),'idempotence');
 const ten=path.join(tmp,'ten');copyRoot(ten);const drugFiles=fs.readdirSync(path.join(ten,'data/drugs')).filter(x=>x.endsWith('.json'));const outsideBefore=new Map(drugFiles.filter(x=>!ids.includes(x.slice(0,-5))).map(x=>[x,sha(fs.readFileSync(path.join(ten,'data/drugs',x)))]));const tenZip=makeZip(ten,ids);r=run(ten,tenZip,['--apply']);assert.equal(r.status,0,r.stderr);const result=JSON.parse(r.stdout);assert.equal(result.ids.length,10);assert.ok(!fs.existsSync(path.join(ten,'public/data/drugs/abacavir.json')));assert.equal(fs.readdirSync(path.join(ten,'public/data/drugs')).filter(x=>x.endsWith('.json')).length,60);for(const [file,beforeHash] of outsideBefore)assert.equal(sha(fs.readFileSync(path.join(ten,'data/drugs',file))),beforeHash,`outside batch changed: ${file}`);const gold70=JSON.parse(fs.readFileSync(path.join(ten,'data/drugs/acetazolamida.json')));assert.equal(Object.keys(gold70.pt).filter(k=>fields.includes(k)).length,33);assert.equal(Object.keys(gold70.es).filter(k=>fields.includes(k)).length,33);
 const rollback=path.join(tmp,'rollback');copyRoot(rollback);const rbZip=makeZip(rollback,ids);const before=sha(fs.readFileSync(path.join(rollback,'database/anticoag.js')));r=run(rollback,rbZip,['--apply'],{GOLD33_FAIL_AFTER_WRITES:'1'});assert.notEqual(r.status,0);assert.equal(sha(fs.readFileSync(path.join(rollback,'database/anticoag.js'))),before,'rollback must restore source');
 const tampered=path.join(tmp,'tampered.zip');fs.copyFileSync(oneZip,tampered);execFileSync('zip',['-q',tampered,'01_DADOS_HOMOLOGADOS.json'],{cwd:path.join(ten,'pkg')});r=run(one,tampered);assert.notEqual(r.status,0,'tampered package rejected');
 execFileSync(process.execPath,['scripts/verify-public-boundary.cjs'],{cwd:ten,stdio:'pipe'});
 console.log(`SINGLE_DRUG_UPDATE=PASS\nTEN_DRUG_UPDATE=PASS\nUNAUTHORIZED_OR_TAMPERED_REJECTION=PASS\nBLOCKED_CALCULATION_PRESERVED=PASS\nOUTSIDE_BATCH_PRESERVED=${outsideBefore.size}/${outsideBefore.size}\nGOLD70_NONLOT_BYTE_PRESERVATION=PASS\nGOLD70_LOT_33_PT_ES=PASS\nPREMIUM_PUBLIC_EXPOSURE=ZERO\nIDEMPOTENCE=PASS\nROLLBACK=PASS\nR30_FREE60_BOUNDARY=PASS\nRESULT=PASS_GOLD33_SELECTIVE_SYNC`);
}finally{fs.rmSync(tmp,{recursive:true,force:true});}
